server:
  compression:
    enabled: true
    min-response-size: 1
  jetty:
    acceptors: 2
  port: 8080
spring:
  application:
    name: spring-boot-activiti
  datasource:
    url: jdbc:mysql://localhost:3306/activiti?useSSL=false&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  activiti:
    database-schema-update: true
    db-history-used: true
logging:
  level:
    org.springfromework: debug
    org.cklxl: debug
mybatis:
  typeAliasesPackage: org.cklxl.activiti
  mapperLocations: classpath:mapper/*.xml
