server:
  compression:
    enabled: true
    min-response-size: 1
  jetty:
    acceptors: 2
  port: 8080
spring:
  application:
    name: spring-boot-jetty
logging:
  level:
    org.springfromework: debug